# Generated by Django 2.2.6 on 2019-11-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherStation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
    ]
