# Generated by Django 2.2.6 on 2019-11-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactTest',
        ),
    ]
