# Generated by Django 2.2.6 on 2019-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20191128_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttest',
            name='attachment',
            field=models.FileField(null=True, upload_to='contact/'),
        ),
    ]
